name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  HUSKY: 0

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write # added for provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Configure git user for GitHub App
        run: |
          git config --global user.name 'marcalexiei'
          git config --global user.email '24919330+marcalexiei@users.noreply.github.com'

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release"
          title: "chore: release"
          publish: "pnpm release"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
